/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("JEB_HOME: " + System.getenv("JEB_HOME"));

        if (System.getenv("JEB_HOME") == null || System.getenv("JEB_HOME").isEmpty()) {
            System.out.println("env JEB_HOME is not set, exit");
            return;
        }

        if (!Utils.checkApktoolExists()) {
            System.out.println("[-] 致命错误: 未在系统环境变量 (PATH) 中找到 apktool！");
            System.out.println("[-] 请确保已安装 Apktool，并在终端中直接输入 'apktool' 可以正常运行。");
            return;
        }

        if (!Utils.checkJadxExists()) {
            System.out.println("[-] Fatal: jadx not found");
            return;
        }

        if (args.length < 2) {
            throw new RuntimeException("no enough args");
        }
        String apkPath = args[0];
        String outDir = args[1];

        try {
            JebClient.decompileApk(apkPath, outDir);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
